AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName:
    Type: String
  S3Version:
    Type: String

Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs14.x
      Code:
        S3Bucket: !Ref BucketName
        S3Key: function.zip
        S3ObjectVersion: !Ref S3Version
      Handler: function/index.handler
      Role: !GetAtt ExecutionRole.Arn

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        